paypal:
  client-id: ASRc5d323YkKuloBIBOTIToWsyy9WXTclMvkB8hgZCN20N3s0b4I7cWCztHK8XE-BcerNX1-X5YNPTV-
  client-secret: EEzWzEx3WzV9KYRlVGq58_hRtD_L2RSd5n0wukzBEsp-w9Y3g7FD-ZFVzHTjJ1SrmPSJu3aE8irpGfwm
  mode: sandbox